schema_version = "1.0.0"

id = "forced_shape_key_transfer"
version = "1.0.0"
name = "Forced Shape Key Transfer"
tagline = "Transfer shape keys between meshes with different topology"
maintainer = "Boon56228"
type = "add-on"

tags = ["Modeling"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 ToPu"]
